### ISSUE TITLE
为什么下载怎么慢

### ISSUE THREAD

**Issue by Yu-App-Studio** [yuzhengyang1/Yu-Studio#1]

**Comment by Yu-App-Studio** [comment]
我捐助了，没有特权
![屏幕截图 2022-03-11 214451](https://user-images.githubusercontent.com/101408184/157880039-3baa97d1-33c6-4940-b270-f91c97519ca9.jpg)

**Comment by yuzhengyang1** [comment]
链接：
       https:/no.deego.noe
